-- require('no-neck-pain').setup({
--   width = 200,
--   buffers = {
--     blend = 0.3,
--     right = {
--       enabled = false,
--     },
--     left = {
--       enabled = false,
--     },
--   },
--   autocmds = {
--     enableOnVimEnter = true,
--     enableOnTabEnter = true,
--     reloadOnColorSchemeChange = true,
--   },
-- })
-- vim.keymap.set('n', '<leader>z', '<cmd>NoNeckPain<CR>')
