local mini_icons_opts = {
  directory = {
    aws = { glyph = '', hl = 'IconAws' },
    supabase = { glyph = '', hl = 'IconSupabase' },
  },
  file = {
    ['package.json'] = { glyph = '', hl = 'DevIconPackageJson' },
    ['package-lock.json'] = { glyph = '', hl = 'DevIconPackageLockJson' },
    ['npm-shrinkwrap.json'] = { glyph = '', hl = 'DevIconJson' },
    ['.npmrc'] = { glyph = '', hl = 'DevIconNPMrc' },
    ['.npmignore'] = { glyph = '', hl = 'DevIconNPMIgnore' },
    ['.dockerignore'] = { glyph = '󰡨', hl = 'DevIconDockerfile' },
    ['compose.yaml'] = { glyph = '󰡨', hl = 'DevIconDockerfile' },
    ['compose.yml'] = { glyph = '󰡨', hl = 'DevIconDockerfile' },
    ['Dockerfile'] = { glyph = '󰡨', hl = 'DevIconDockerfile' },
    ['dockerfile'] = { glyph = '󰡨', hl = 'DevIconDockerfile' },
    ['docker-compose.yaml'] = { glyph = '󰡨', hl = 'DevIconDockerfile' },
    ['docker-compose.yml'] = { glyph = '󰡨', hl = 'DevIconDockerfile' },
    ['pnpm-lock.yaml'] = { glyph = '', hl = 'DevIconPNPMLock' },
    ['pnpm-workspace.yaml'] = { glyph = '', hl = 'DevIconPNPMWorkspace' },
    ['.pnpmfile.cjs'] = { glyph = '', hl = 'DevIconPNPMFile' },
    ['tsconfig.json'] = { glyph = '', hl = 'DevIconTSConfig' },
    ['tsconfig.app.json'] = { glyph = '', hl = 'DevIconTSConfig' },
    ['tsconfig.base.json'] = { glyph = '', hl = 'DevIconTSConfig' },
    ['tsconfig.build.json'] = { glyph = '', hl = 'DevIconTSConfig' },
    ['tsconfig.dev.json'] = { glyph = '', hl = 'DevIconTSConfig' },
    ['tsconfig.eslint.json'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['tsconfig.lib.json'] = { glyph = '', hl = 'DevIconTSConfig' },
    ['tsconfig.node.json'] = { glyph = '', hl = 'DevIconTSConfig' },
    ['tsconfig.prod.json'] = { glyph = '', hl = 'DevIconTSConfig' },
    ['tsconfig.spec.json'] = { glyph = '', hl = 'DevIconTSConfig' },
    ['tsconfig.test.json'] = { glyph = '', hl = 'DevIconTSConfig' },
    ['.eslintrc'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['.eslintrc.js'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['.eslintrc.cjs'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['.eslintrc.mjs'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['.eslintrc.json'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['.eslintrc.yaml'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['.eslintrc.yml'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['.eslintignore'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['eslint.config.js'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['eslint.config.cjs'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['eslint.config.mjs'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['eslint.config.ts'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['eslint.config.mts'] = { glyph = '', hl = 'DevIconEslintrc' },
    ['tailwind.config.js'] = { glyph = '󱏿', hl = 'DevIconTailwindConfig' },
    ['tailwind.config.cjs'] = { glyph = '󱏿', hl = 'DevIconTailwindConfig' },
    ['tailwind.config.mjs'] = { glyph = '󱏿', hl = 'DevIconTailwindConfig' },
    ['tailwind.config.ts'] = { glyph = '󱏿', hl = 'DevIconTailwindConfig' },
    ['tailwind.config.mts'] = { glyph = '󱏿', hl = 'DevIconTailwindConfig' },
    ['tailwind.config.cts'] = { glyph = '󱏿', hl = 'DevIconTailwindConfig' },
    ['deno.json'] = { glyph = '', hl = 'IconDeno' },
    ['deno.jsonc'] = { glyph = '', hl = 'IconDeno' },
    ['deno.lock'] = { glyph = '', hl = 'IconDeno' },
    ['deno.ts'] = { glyph = '', hl = 'IconDeno' },
    ['deno.config.ts'] = { glyph = '', hl = 'IconDeno' },
    ['deno.config.js'] = { glyph = '', hl = 'IconDeno' },
    ['deno.config.mjs'] = { glyph = '', hl = 'IconDeno' },
    ['deno.config.cjs'] = { glyph = '', hl = 'IconDeno' },
    ['.babelrc'] = { glyph = '󰨥', hl = 'DevIconBabelrc' },
    ['.babelrc.js'] = { glyph = '󰨥', hl = 'DevIconBabelrc' },
    ['.babelrc.cjs'] = { glyph = '󰨥', hl = 'DevIconBabelrc' },
    ['.babelrc.mjs'] = { glyph = '󰨥', hl = 'DevIconBabelrc' },
    ['.babelrc.json'] = { glyph = '󰨥', hl = 'DevIconBabelrc' },
    ['babel.config.js'] = { glyph = '󰨥', hl = 'DevIconBabelrc' },
    ['babel.config.cjs'] = { glyph = '󰨥', hl = 'DevIconBabelrc' },
    ['babel.config.mjs'] = { glyph = '󰨥', hl = 'DevIconBabelrc' },
    ['babel.config.json'] = { glyph = '󰨥', hl = 'DevIconBabelrc' },
    ['next.config.js'] = { glyph = '', hl = 'DevIconNextConfigJs' },
    ['next.config.cjs'] = { glyph = '', hl = 'DevIconNextConfigJs' },
    ['next.config.mjs'] = { glyph = '', hl = 'DevIconNextConfigJs' },
    ['next.config.ts'] = { glyph = '', hl = 'DevIconNextConfigJs' },
    ['next.config.cts'] = { glyph = '', hl = 'DevIconNextConfigJs' },
    ['next.config.mts'] = { glyph = '', hl = 'DevIconNextConfigJs' },
    ['next-env.d.ts'] = { glyph = '', hl = 'DevIconNextConfigJs' },
    ['vitest.config.js'] = { glyph = '', hl = 'DevIconVitestConfig' },
    ['vitest.config.cjs'] = { glyph = '', hl = 'DevIconVitestConfig' },
    ['vitest.config.mjs'] = { glyph = '', hl = 'DevIconVitestConfig' },
    ['vitest.config.ts'] = { glyph = '', hl = 'DevIconVitestConfig' },
    ['vitest.config.cts'] = { glyph = '', hl = 'DevIconVitestConfig' },
    ['vitest.config.mts'] = { glyph = '', hl = 'DevIconVitestConfig' },
    ['vitest.workspace.js'] = { glyph = '', hl = 'DevIconVitestConfig' },
    ['vitest.workspace.ts'] = { glyph = '', hl = 'DevIconVitestConfig' },
    ['vitest.setup.js'] = { glyph = '', hl = 'DevIconVitestConfig' },
    ['vitest.setup.ts'] = { glyph = '', hl = 'DevIconVitestConfig' },
    ['vite.config.js'] = { glyph = '', hl = 'DevIconViteConfig' },
    ['vite.config.cjs'] = { glyph = '', hl = 'DevIconViteConfig' },
    ['vite.config.mjs'] = { glyph = '', hl = 'DevIconViteConfig' },
    ['vite.config.ts'] = { glyph = '', hl = 'DevIconViteConfig' },
    ['vite.config.cts'] = { glyph = '', hl = 'DevIconViteConfig' },
    ['vite.config.mts'] = { glyph = '', hl = 'DevIconViteConfig' },
    ['vite-env.d.ts'] = { glyph = '', hl = 'DevIconViteConfig' },
    ['playwright.config.js'] = { glyph = '', hl = 'DevIconPlaywrightConfig' },
    ['playwright.config.cjs'] = { glyph = '', hl = 'DevIconPlaywrightConfig' },
    ['playwright.config.mjs'] = { glyph = '', hl = 'DevIconPlaywrightConfig' },
    ['playwright.config.ts'] = { glyph = '', hl = 'DevIconPlaywrightConfig' },
    ['playwright.config.cts'] = { glyph = '', hl = 'DevIconPlaywrightConfig' },
    ['playwright.config.mts'] = { glyph = '', hl = 'DevIconPlaywrightConfig' },
    ['playwright-ct.config.js'] = { glyph = '', hl = 'DevIconPlaywrightConfig' },
    ['playwright-ct.config.ts'] = { glyph = '', hl = 'DevIconPlaywrightConfig' },
    ['postcss.config.js'] = { glyph = '', hl = 'IconPostCSS' },
    ['postcss.config.cjs'] = { glyph = '', hl = 'IconPostCSS' },
    ['postcss.config.mjs'] = { glyph = '', hl = 'IconPostCSS' },
    ['postcss.config.ts'] = { glyph = '', hl = 'IconPostCSS' },
    ['postcss.config.cts'] = { glyph = '', hl = 'IconPostCSS' },
    ['postcss.config.mts'] = { glyph = '', hl = 'IconPostCSS' },
    ['postcss.config.json'] = { glyph = '', hl = 'IconPostCSS' },
    ['.postcssrc'] = { glyph = '', hl = 'IconPostCSS' },
    ['.postcssrc.js'] = { glyph = '', hl = 'IconPostCSS' },
    ['.postcssrc.cjs'] = { glyph = '', hl = 'IconPostCSS' },
    ['.postcssrc.mjs'] = { glyph = '', hl = 'IconPostCSS' },
    ['.postcssrc.json'] = { glyph = '', hl = 'IconPostCSS' },
    ['.postcssrc.yaml'] = { glyph = '', hl = 'IconPostCSS' },
    ['.postcssrc.yml'] = { glyph = '', hl = 'IconPostCSS' },
    ['vercel.json'] = { glyph = '', hl = 'DevIconVercel' },
    ['vercel.jsonc'] = { glyph = '', hl = 'DevIconVercel' },
    ['.vercelignore'] = { glyph = '', hl = 'DevIconVercel' },
    ['vercel.config.js'] = { glyph = '', hl = 'DevIconVercel' },
    ['vercel.config.cjs'] = { glyph = '', hl = 'DevIconVercel' },
    ['vercel.config.mjs'] = { glyph = '', hl = 'DevIconVercel' },
    ['vercel.config.ts'] = { glyph = '', hl = 'DevIconVercel' },
    ['vercel.config.cts'] = { glyph = '', hl = 'DevIconVercel' },
    ['vercel.config.mts'] = { glyph = '', hl = 'DevIconVercel' },
    ['now.json'] = { glyph = '', hl = 'DevIconVercel' },
    ['.nowignore'] = { glyph = '', hl = 'DevIconVercel' },
  },
}

local function set_icon_highlights()
  vim.api.nvim_set_hl(0, 'IconAws', { fg = '#FF9900' })
  vim.api.nvim_set_hl(0, 'IconDeno', { fg = '#000000' })
  vim.api.nvim_set_hl(0, 'IconPostCSS', { fg = '#DD3A0A' })
  vim.api.nvim_set_hl(0, 'IconSupabase', { fg = '#3ECF8E' })
end

return {
  {
    'echasnovski/mini.icons',
    lazy = false,
    opts = mini_icons_opts,
    init = function()
      local group = vim.api.nvim_create_augroup('MiniIconsCustomHighlights', { clear = true })
      vim.api.nvim_create_autocmd('ColorScheme', {
        group = group,
        callback = set_icon_highlights,
      })
      set_icon_highlights()
    end,
  },
}
